"""Build Ironmate Pages examples from vendored web-ui v1 emitters.

The sibling projects own the emitters. Ironmate owns composition with pinned
web-ui assets and the published examples.
"""

from __future__ import annotations

from pathlib import Path

from vendor import ascii_artist, markdown

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "docs" / "consumer-v1"

WEB_UI_SHA = "dfdbb26a76f71b147483f212ec49ca677384b936"
MARKDOWN_SHA = "83a325ce573670b7e6723c113648822502a33bed"
ASCII_ARTIST_SHA = "7c21bacfac7b60327b77f9b31a87869ef7838a7e"

_WEB_UI_BASE = (
    "https://cdn.jsdelivr.net/gh/myon-bioinformatics/"
    f"web-ui@{WEB_UI_SHA}"
)
_STYLESHEETS = (
    "css/tokens.css",
    "css/base.css",
    "css/components.css",
    "css/stub.css",
    "css/themes/modern.css",
)


def _attach_web_ui_assets(document: str) -> str:
    links = "\n".join(
        f'<link rel="stylesheet" href="{_WEB_UI_BASE}/{path}">'
        for path in _STYLESHEETS
    )
    marker = "</head>"
    if marker not in document:
        raise ValueError("web-ui v1 emitter document is missing </head>")
    provenance = (
        f"<!-- Ironmate consumer integration: web-ui={WEB_UI_SHA} "
        f"markdown={MARKDOWN_SHA} ascii_artist={ASCII_ARTIST_SHA} -->"
    )
    return document.replace(marker, f"{links}\n{provenance}\n{marker}", 1)


def build_documents() -> dict[str, str]:
    markdown_source = """# Ironmate consumer integration

This page is generated by the vendored **markdown.py** web-ui v1 emitter.

- semantic HTML stays in the library
- CSS stays consumer-owned
- web-ui assets are pinned by Ironmate
"""
    markdown_page = _attach_web_ui_assets(
        markdown.markdown_to_web_ui_v1(
            markdown_source,
            title="Markdown → web-ui v1",
            theme="modern",
        )
    )

    diagram = ascii_artist.diagram(
        [
            ascii_artist.Node("markdown", "markdown.py"),
            ascii_artist.Node("ascii", "ascii_artist.py"),
            ascii_artist.Node("contract", "web-ui contract v1"),
            ascii_artist.Node("ironmate", "Ironmate"),
        ],
        [
            ("markdown", "contract"),
            ("ascii", "contract"),
            ("contract", "ironmate"),
        ],
    )
    ascii_page = _attach_web_ui_assets(
        ascii_artist.to_web_ui_v1_html(
            diagram,
            title="ascii_artist → web-ui v1",
            theme="modern",
        )
    )

    index_page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ironmate web-ui v1 consumers</title>
{chr(10).join(f'<link rel="stylesheet" href="{_WEB_UI_BASE}/{path}">' for path in _STYLESHEETS)}
</head>
<body data-ui-theme="modern">
<main class="ui-page">
<h1 class="ui-title">Ironmate · web-ui v1 consumers</h1>
<p class="ui-muted">Generated from pinned vendored upstream emitters.</p>
<section class="ui-grid">
<article class="ui-card"><h2>Markdown</h2><p><a href="./markdown.html">Open generated Markdown example</a></p></article>
<article class="ui-card"><h2>ASCII / Diagram</h2><p><a href="./ascii.html">Open generated ASCII example</a></p></article>
</section>
<pre class="ui-output">web-ui {WEB_UI_SHA[:8]}
markdown {MARKDOWN_SHA[:8]}
ascii_artist {ASCII_ARTIST_SHA[:8]}</pre>
</main>
</body>
</html>
"""
    return {
        "index.html": index_page,
        "markdown.html": markdown_page,
        "ascii.html": ascii_page,
    }


def write_documents(output_dir: Path = OUTPUT_DIR) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in build_documents().items():
        (output_dir / name).write_text(content, encoding="utf-8")


if __name__ == "__main__":
    write_documents()
